# Copyright 2025 Scott Friedman. All rights reserved.
# golangci-lint configuration for Go Report Card Grade A

version: 2

run:
  timeout: 5m
  tests: true
  go: '1.21'

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst
    - gocyclo
    - unconvert
    - unparam
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam
    - path: cmd/
      text: "should have comment"