# Copyright 2025 Scott Friedman. All rights reserved.
# golangci-lint configuration for Go Report Card grade A

version: 2

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

linters-settings:
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck